In [9]:
import numpy as np

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5],
                 [6, 8, 9]])

print(arr)
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)

[[1 2 3]
 [4 2 5]
 [6 8 9]]
No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9


In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr)
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
No. of dimensions:  3
Shape of array:  (2, 2, 2)
Size of array:  8
