In [43]:
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x,"\n")
print(x.ndim)
x.shape

[0 1 2 3 4 5 6 7 8 9] 

1


(10,)

In [44]:
y = array[np.newaxis, :]
print(y,"\n")
print(y.ndim)
print(y.shape)

[[0 1 2 3 4 5 6 7 8 9]] 

2
(1, 10)


In [48]:
y = np.expand_dims(x, axis=0)
print(y,"\n")
print(y.ndim)

[[0 1 2 3 4 5 6 7 8 9]] 

2


In [46]:
y.shape

(1, 10)