In [1]:
import numpy as np 
  
a = np.array([[2, 4], 
              [3, 9]]) 
  
b = np.array([[5, 25], 
              [6, 36]]) 

print("Vertical stacking:\n", np.vstack((a, b)))

Vertical stacking:
 [[ 2  4]
 [ 3  9]
 [ 5 25]
 [ 6 36]]


In [2]:
print("\nHorizontal stacking:\n", np.hstack((a, b)))


Horizontal stacking:
 [[ 2  4  5 25]
 [ 3  9  6 36]]
